# Generated by Django 5.0.6 on 2024-06-06 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_task_scheduled_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='scheduled_date',
        ),
    ]
