# Generated by Django 5.0.6 on 2024-06-09 14:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_project_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_added',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
