# Generated by Django 5.0.6 on 2024-06-06 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='description',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='due_date',
        ),
    ]
