# Generated by Django 5.0.6 on 2024-06-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_plan_description_remove_plan_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='images/avatar1.png', upload_to='profile_images/'),
        ),
    ]
