# Generated by Django 5.0.6 on 2024-06-07 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_profile_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_image',
        ),
    ]
